# Generated by Django 5.0.7 on 2024-07-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Post',
        ),
    ]
